name: extraUtils
version: '${project.version}'
main: com.velocitypowered.extrautils.ExtraUtils
api-version: '1.20'
load: STARTUP
author: def1de

commands:
  extrautils:
    description: Extrautils main command